In [6]:
%matplotlib inline

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
dataset=pd.read_csv('data[1].csv')
dataset

layer_height  wall_thickness  infill_density infill_pattern  \
0           0.02               8              90           grid   
1           0.02               7              90      honeycomb   
2           0.02               1              80           grid   
3           0.02               4              70      honeycomb   
4           0.02               6              90           grid   
5           0.02              10              40      honeycomb   
6           0.02               5              10           grid   
7           0.02              10              10      honeycomb   
8           0.02               9              70           grid   
9           0.02               8              40      honeycomb   
10          0.06               6              80           grid   
11          0.06               2              20      honeycomb   
12          0.06              10              50           grid   
13          0.06               6              10      honeycomb   
14          0.06               3              50           grid   
15          0.06              10              90      honeycomb   
16          0.06               3              40           grid   
17          0.06               8              30      honeycomb   
18          0.06               5              80           grid   
19          0.06              10              50      honeycomb   
20          0.10               1              40           grid   
21          0.10               2              30      honeycomb   
22          0.10               1              50           grid   
23          0.10               9              80      honeycomb   
24          0.10               2              60           grid   
25          0.10               1              50      honeycomb   
26          0.10               4              40           grid   
27          0.10               3              50      honeycomb   
28          0.10               4              90           grid   
29          0.10               1              30      honeycomb   
30          0.15               4              50           grid   
31          0.15               7              10      honeycomb   
32          0.15               6              50           grid   
33          0.15               1              50      honeycomb   
34          0.15               7              80           grid   
35          0.15               3              80      honeycomb   
36          0.15               4              50           grid   
37          0.15              10              30      honeycomb   
38          0.15               6              40           grid   
39          0.15               1              10      honeycomb   
40          0.20               4              80           grid   
41          0.20               9              90      honeycomb   
42          0.20               7              30           grid   
43          0.20               6              90      honeycomb   
44          0.20               3              80           grid   
45          0.20               5              60      honeycomb   
46          0.20               4              20           grid   
47          0.20               5              60      honeycomb   
48          0.20               7              40           grid   
49          0.20               3              60      honeycomb   

    nozzle_temperature  bed_temperature  print_speed material  fan_speed  \
0                  220               60           40      abs          0   
1                  225               65           40      abs         25   
2                  230               70           40      abs         50   
3                  240               75           40      abs         75   
4                  250               80           40      abs        100   
5                  200               60           40      pla          0   
6                  205               65           40  

In [9]:
dataset.isnull().any()

layer_height          False
wall_thickness        False
infill_density        False
infill_pattern        False
nozzle_temperature    False
bed_temperature       False
print_speed           False
material              False
fan_speed             False
roughness             False
tension_strenght      False
elongation            False
dtype: bool

In [21]:
x = dataset.iloc[:, dataset.columns != 'material']
x

layer_height  wall_thickness  infill_density infill_pattern  \
0           0.02               8              90           grid   
1           0.02               7              90      honeycomb   
2           0.02               1              80           grid   
3           0.02               4              70      honeycomb   
4           0.02               6              90           grid   
5           0.02              10              40      honeycomb   
6           0.02               5              10           grid   
7           0.02              10              10      honeycomb   
8           0.02               9              70           grid   
9           0.02               8              40      honeycomb   
10          0.06               6              80           grid   
11          0.06               2              20      honeycomb   
12          0.06              10              50           grid   
13          0.06               6              10      honeycomb   
14          0.06               3              50           grid   
15          0.06              10              90      honeycomb   
16          0.06               3              40           grid   
17          0.06               8              30      honeycomb   
18          0.06               5              80           grid   
19          0.06              10              50      honeycomb   
20          0.10               1              40           grid   
21          0.10               2              30      honeycomb   
22          0.10               1              50           grid   
23          0.10               9              80      honeycomb   
24          0.10               2              60           grid   
25          0.10               1              50      honeycomb   
26          0.10               4              40           grid   
27          0.10               3              50      honeycomb   
28          0.10               4              90           grid   
29          0.10               1              30      honeycomb   
30          0.15               4              50           grid   
31          0.15               7              10      honeycomb   
32          0.15               6              50           grid   
33          0.15               1              50      honeycomb   
34          0.15               7              80           grid   
35          0.15               3              80      honeycomb   
36          0.15               4              50           grid   
37          0.15              10              30      honeycomb   
38          0.15               6              40           grid   
39          0.15               1              10      honeycomb   
40          0.20               4              80           grid   
41          0.20               9              90      honeycomb   
42          0.20               7              30           grid   
43          0.20               6              90      honeycomb   
44          0.20               3              80           grid   
45          0.20               5              60      honeycomb   
46          0.20               4              20           grid   
47          0.20               5              60      honeycomb   
48          0.20               7              40           grid   
49          0.20               3              60      honeycomb   

    nozzle_temperature  bed_temperature  print_speed  fan_speed  roughness  \
0                  220               60           40          0         25   
1                  225               65           40         25         32   
2                  230               70           40         50         40   
3                  240               75           40         75         68   
4                  250               80           40        100         92   
5                  200               60           40          0         60   
6                  205               65 

In [23]:
# x=dataset.iloc[:,0:7].values
# x

In [16]:
y=dataset.iloc[:,7:8].values
y

array([['abs'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['abs'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['pla'],
       ['pla']], dtype=object)

In [81]:
x.ndim

2

In [82]:
y.ndim

2

In [24]:
# z=dataset.iloc[:,8:]
# z

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [58]:
ct=ColumnTransformer([("on",OneHotEncoder(),[0])],remainder="passthrough")
x=ct.fit_transform(x)
x

array([[1.0, 0.0, 0.02, 8, 90, 220, 60, 40],
       [0.0, 1.0, 0.02, 7, 90, 225, 65, 40],
       [1.0, 0.0, 0.02, 1, 80, 230, 70, 40],
       [0.0, 1.0, 0.02, 4, 70, 240, 75, 40],
       [1.0, 0.0, 0.02, 6, 90, 250, 80, 40],
       [0.0, 1.0, 0.02, 10, 40, 200, 60, 40],
       [1.0, 0.0, 0.02, 5, 10, 205, 65, 40],
       [0.0, 1.0, 0.02, 10, 10, 210, 70, 40],
       [1.0, 0.0, 0.02, 9, 70, 215, 75, 40],
       [0.0, 1.0, 0.02, 8, 40, 220, 80, 40],
       [1.0, 0.0, 0.06, 6, 80, 220, 60, 60],
       [0.0, 1.0, 0.06, 2, 20, 225, 65, 60],
       [1.0, 0.0, 0.06, 10, 50, 230, 70, 60],
       [0.0, 1.0, 0.06, 6, 10, 240, 75, 60],
       [1.0, 0.0, 0.06, 3, 50, 250, 80, 60],
       [0.0, 1.0, 0.06, 10, 90, 200, 60, 60],
       [1.0, 0.0, 0.06, 3, 40, 205, 65, 60],
       [0.0, 1.0, 0.06, 8, 30, 210, 70, 60],
       [1.0, 0.0, 0.06, 5, 80, 215, 75, 60],
       [0.0, 1.0, 0.06, 10, 50, 220, 80, 60],
       [1.0, 0.0, 0.1, 1, 40, 220, 60, 120],
       [0.0, 1.0, 0.1, 2, 30, 225, 65, 120],
     

In [59]:
x.shape

(50, 8)

In [60]:
x=x[:,1:]
x

array([[0.0, 0.02, 8, 90, 220, 60, 40],
       [1.0, 0.02, 7, 90, 225, 65, 40],
       [0.0, 0.02, 1, 80, 230, 70, 40],
       [1.0, 0.02, 4, 70, 240, 75, 40],
       [0.0, 0.02, 6, 90, 250, 80, 40],
       [1.0, 0.02, 10, 40, 200, 60, 40],
       [0.0, 0.02, 5, 10, 205, 65, 40],
       [1.0, 0.02, 10, 10, 210, 70, 40],
       [0.0, 0.02, 9, 70, 215, 75, 40],
       [1.0, 0.02, 8, 40, 220, 80, 40],
       [0.0, 0.06, 6, 80, 220, 60, 60],
       [1.0, 0.06, 2, 20, 225, 65, 60],
       [0.0, 0.06, 10, 50, 230, 70, 60],
       [1.0, 0.06, 6, 10, 240, 75, 60],
       [0.0, 0.06, 3, 50, 250, 80, 60],
       [1.0, 0.06, 10, 90, 200, 60, 60],
       [0.0, 0.06, 3, 40, 205, 65, 60],
       [1.0, 0.06, 8, 30, 210, 70, 60],
       [0.0, 0.06, 5, 80, 215, 75, 60],
       [1.0, 0.06, 10, 50, 220, 80, 60],
       [0.0, 0.1, 1, 40, 220, 60, 120],
       [1.0, 0.1, 2, 30, 225, 65, 120],
       [0.0, 0.1, 1, 50, 230, 70, 120],
       [1.0, 0.1, 9, 80, 240, 75, 120],
       [0.0, 0.1, 2, 60, 250, 80, 1

In [61]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [62]:
x[:,0]=lb.fit_transform(x[:,0])
x

array([[0, 0.02, 8, 90, 220, 60, 40],
       [1, 0.02, 7, 90, 225, 65, 40],
       [0, 0.02, 1, 80, 230, 70, 40],
       [1, 0.02, 4, 70, 240, 75, 40],
       [0, 0.02, 6, 90, 250, 80, 40],
       [1, 0.02, 10, 40, 200, 60, 40],
       [0, 0.02, 5, 10, 205, 65, 40],
       [1, 0.02, 10, 10, 210, 70, 40],
       [0, 0.02, 9, 70, 215, 75, 40],
       [1, 0.02, 8, 40, 220, 80, 40],
       [0, 0.06, 6, 80, 220, 60, 60],
       [1, 0.06, 2, 20, 225, 65, 60],
       [0, 0.06, 10, 50, 230, 70, 60],
       [1, 0.06, 6, 10, 240, 75, 60],
       [0, 0.06, 3, 50, 250, 80, 60],
       [1, 0.06, 10, 90, 200, 60, 60],
       [0, 0.06, 3, 40, 205, 65, 60],
       [1, 0.06, 8, 30, 210, 70, 60],
       [0, 0.06, 5, 80, 215, 75, 60],
       [1, 0.06, 10, 50, 220, 80, 60],
       [0, 0.1, 1, 40, 220, 60, 120],
       [1, 0.1, 2, 30, 225, 65, 120],
       [0, 0.1, 1, 50, 230, 70, 120],
       [1, 0.1, 9, 80, 240, 75, 120],
       [0, 0.1, 2, 60, 250, 80, 120],
       [1, 0.1, 1, 50, 200, 60, 120],
       

In [63]:
feat_labels=['layer_height','wall_thickness','infill_density','infill_pattern','nozzle_temperature','bed_temperature','print_speed','fan_speed','roughness','tension_strenght','elongation']

In [64]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [65]:
x_train

array([[1, 0.15, 1, 50, 240, 75, 60],
       [1, 0.15, 3, 80, 200, 60, 60],
       [0, 0.1, 4, 40, 205, 65, 120],
       [0, 0.15, 7, 80, 250, 80, 60],
       [0, 0.06, 5, 80, 215, 75, 60],
       [1, 0.02, 10, 10, 210, 70, 40],
       [0, 0.06, 3, 50, 250, 80, 60],
       [1, 0.2, 5, 60, 200, 60, 40],
       [0, 0.2, 7, 40, 215, 75, 40],
       [1, 0.1, 1, 30, 220, 80, 120],
       [1, 0.06, 10, 90, 200, 60, 60],
       [0, 0.15, 4, 50, 220, 60, 60],
       [0, 0.15, 6, 50, 230, 70, 60],
       [0, 0.06, 3, 40, 205, 65, 60],
       [0, 0.2, 7, 30, 230, 70, 40],
       [0, 0.1, 1, 40, 220, 60, 120],
       [1, 0.2, 6, 90, 240, 75, 40],
       [0, 0.02, 9, 70, 215, 75, 40],
       [1, 0.06, 6, 10, 240, 75, 60],
       [1, 0.1, 1, 50, 200, 60, 120],
       [1, 0.02, 10, 40, 200, 60, 40],
       [1, 0.06, 8, 30, 210, 70, 60],
       [0, 0.2, 4, 80, 220, 60, 40],
       [1, 0.2, 3, 60, 220, 80, 40],
       [1, 0.02, 7, 90, 225, 65, 40],
       [0, 0.06, 10, 50, 230, 70, 60],
       [1, 0.1

In [66]:
y_train

array([[0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0]], dtype=object)